-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.touren
    ADD COLUMN published boolean DEFAULT false;

COMMENT ON COLUMN public.touren.published
    IS 'Is tour published';

CREATE POLICY "All:Select_published"
    ON public.touren
    AS PERMISSIVE
    FOR SELECT
    TO anon
    USING ((published = true));

CREATE POLICY "Admin:Select_all"
    ON public.touren
    AS PERMISSIVE
    FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "All:Select" ON public.touren;
