create table "public"."tour_dates" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "tour_date" timestamp with time zone,
    "meeting_point" text,
    "is_canceled" boolean not null default false
);


alter table "public"."tour_dates" enable row level security;

alter table "public"."touren" drop column "image";

CREATE UNIQUE INDEX tour_dates_pkey ON public.tour_dates USING btree (id);

alter table "public"."tour_dates" add constraint "tour_dates_pkey" PRIMARY KEY using index "tour_dates_pkey";

create policy "Admin:Insert"
on "public"."tour_dates"
as permissive
for insert
to authenticated
with check (true);


create policy "Admin:Select"
on "public"."tour_dates"
as permissive
for select
to authenticated
using (true);


create policy "Admin:Update"
on "public"."tour_dates"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "All:Select_current"
on "public"."tour_dates"
as permissive
for select
to anon
using (true);



